#!/usr/bin/env python3
"""sdk-index.py — Vectorworks SDK の宣言索引（`SDK Index/`）を生成する。

なぜこれがあるか
----------------
リモートセッション（クラウド上のコンテナ）には SDK が無く、「この関数のシグネチャは」
「この enum にどんな値があるか」を確かめるたびに ci-debug（sdk-grep）を 1 往復させて
いた。宣言の一覧はリポジトリに置いておけば `Grep` 一発で引ける。SDK の更新は年に数回
なので、週次の CI（.github/workflows/sdk-index.yml）で作り直し、差分があれば PR にする。

何を載せるか（載せないか）
--------------------------
**宣言だけ**を載せる。名前・種類・宣言文（シグネチャ）・場所（ファイル:行）。
**コメントと関数本体は載せない**——SDK をそのまま再配布しないため（ユーザーと決めた
方針。CLAUDE.md「SDK の宣言索引」）。説明や実装を読みたいときは今まで通り
ci-debug の sdk-grep / sdk-ls で原本を引く。

  - Include/ と Source/ の C++（.h .hpp .inl .cpp）を universal-ctags で読む。
    サードパーティ（glm / json）と、ISDK の写しでしかない MockUp は除く。
  - 宣言文は ctags の signature からではなく**原本の該当行から**組み立てる。ctags は
    既定引数・`virtual`・`= 0`・`const` を落とすため（5.9 では properties も取れない）。
    コメントはここで剥がす。
  - Include/vs.py（VectorScript / Python の関数定義）は別表 `VectorScript.md` に
    シグネチャと分類だけを載せる（説明文は載せない）。

出力は決定的（同じ SDK からは同じバイト列）であること。生成日時のような毎回変わる
ものを入れると、週次の CI が毎回 PR を立ててしまう。

使い方
------
    scripts/sdk-index.py <SDK_DIR> <OUT_DIR>

  SDK_DIR  scripts/fetch-vw-sdk.sh が用意した場所（この下に SDKLib/ がある）
  OUT_DIR  書き出し先（既定の置き場は `SDK Index`）。中の生成物は丸ごと作り直す。
"""

import collections
import json
import os
import re
import shutil
import subprocess
import sys

# ctags に読ませない（サードパーティ・写し）。パスの部分一致ではなくディレクトリ名。
EXCLUDE_DIRS = ["glm", "json", "MockUp"]

# 宣言に紛れ込むが意味の無いマクロ。ctags にも空として教え、表示からも消す。
NOISE_MACROS = ["VCOM_CALLTYPE", "GS_CALLBACK", "GS_API", "GS_HIDDEN_VISIBILITY"]

# 載せる種類と、見出しに出す順。local / parameter などは載せない（ctags 側で切る）。
KIND_ORDER = [
    "namespace",
    "class",
    "struct",
    "union",
    "enum",
    "enumerator",
    "typedef",
    "macro",
    "variable",
    "member",
    "prototype",
    "function",
]

# 1 件の宣言文の長さの上限。複数行にまたがる巨大なマクロや初期化子で行が膨らむのを防ぐ。
MAX_DECL = 400

# 生成物であることの印。この印を持つファイルだけを作り直しの際に消す。
GENERATED_MARK = "<!-- generated by scripts/sdk-index.py; do not edit by hand -->"


def die(msg):
    print(f"sdk-index: error: {msg}", file=sys.stderr)
    sys.exit(1)


def run_ctags(sdklib):
    cmd = [
        "ctags",
        "-R",
        "--languages=C++",
        "--langmap=C++:+.h.inl",
        "--kinds-C++=+p-l-z-L-D",
        "--fields=+nSti-f",
        "--fields=+K",
        "--extras=-f",
        "--sort=no",
        "--output-format=json",
        "-f",
        "-",
    ]
    for m in NOISE_MACROS:
        cmd.append(f"-D{m}=")
    for d in EXCLUDE_DIRS:
        cmd.append(f"--exclude={d}")
    cmd += ["Include", "Source"]
    out = subprocess.run(cmd, cwd=sdklib, check=True, capture_output=True, text=True).stdout
    tags = []
    for line in out.splitlines():
        if not line.strip():
            continue
        t = json.loads(line)
        if t.get("_type") != "tag":
            continue
        if t.get("kind") not in KIND_ORDER:
            continue
        tags.append(t)
    return tags


# --- 原本の読み出し --------------------------------------------------------

_file_cache = {}


def source_lines(sdklib, path):
    if path not in _file_cache:
        with open(os.path.join(sdklib, path), "rb") as f:
            raw = f.read()
        # SDK には UTF-8 と Shift_JIS 等が混在する。落とさず読めればよい（宣言は ASCII）。
        text = raw.decode("utf-8", errors="replace").replace("\r\n", "\n").replace("\r", "\n")
        _file_cache[path] = text.split("\n")
    return _file_cache[path]


_block_comment = re.compile(r"/\*.*?\*/", re.S)
_line_comment = re.compile(r"//[^\n]*")
_noise = re.compile(r"\b(?:" + "|".join(NOISE_MACROS) + r")\b")
_space = re.compile(r"\s+")


def strip_comments(text):
    text = _block_comment.sub(" ", text)
    # 閉じていない /* （宣言の途中で打ち切ったとき）以降は捨てる。
    i = text.find("/*")
    if i >= 0:
        text = text[:i]
    return _line_comment.sub(" ", text)


def tidy(text):
    text = _noise.sub(" ", text)
    text = _space.sub(" ", text).strip()
    text = re.sub(r"\( ", "(", text)
    text = re.sub(r" \)", ")", text)
    text = re.sub(r" ,", ",", text)
    text = re.sub(r" ;", ";", text)
    if len(text) > MAX_DECL:
        text = text[: MAX_DECL - 1].rstrip() + "…"
    return text


def gather(lines, start, stop_at_brace, max_lines=40):
    """start 行（0 始まり）から、括弧の外で ; か { が来るまでを 1 本の文字列にする。"""
    buf = []
    depth = 0
    for i in range(start, min(len(lines), start + max_lines)):
        line = strip_comments(lines[i])
        for j, ch in enumerate(line):
            if ch in "([":
                depth += 1
            elif ch in ")]":
                depth = max(0, depth - 1)
            elif depth == 0 and (ch == ";" or (ch == "{" and stop_at_brace)):
                buf.append(line[: j + (1 if ch == ";" else 0)])
                return " ".join(buf)
        buf.append(line)
    return " ".join(buf)


def decl_of(sdklib, t):
    kind = t["kind"]
    lines = source_lines(sdklib, t["path"])
    idx = t["line"] - 1
    if idx < 0 or idx >= len(lines):
        return ""

    if kind == "macro":
        # #define は 1 行目だけ（継続行 \ の先は本体なので載せない）。
        line = strip_comments(lines[idx]).rstrip()
        if line.endswith("\\"):
            line = line[:-1].rstrip() + " …"
        return tidy(line)

    if kind in ("enumerator", "member", "variable"):
        # 1 行に収まるのが普通。列挙子は値ごと出す（`kFoo = 3,`）。
        if kind == "enumerator":
            return tidy(strip_comments(lines[idx]))
        text = gather(lines, idx, stop_at_brace=True, max_lines=6)
        word = re.compile(r"\b" + re.escape(t["name"]) + r"\b")
        if not word.search(text):
            # 1 行に文が並ぶ書き方（`const short kWallNode = 68;	const short kWallProp = …;`）。
            # 名前を含む文を選ぶ。
            for stmt in strip_comments(lines[idx]).split(";"):
                if word.search(stmt):
                    return tidy(stmt + ";")
        return tidy(text)

    if kind in ("namespace", "class", "struct", "union", "enum"):
        text = gather(lines, idx, stop_at_brace=True, max_lines=8)
        return tidy(text.rstrip("{ ").rstrip())

    # prototype / function / typedef: 宣言文。本体（{ 以降）は捨てる。
    text = gather(lines, idx, stop_at_brace=True)
    text = tidy(text)
    if kind in ("prototype", "function"):
        # 戻り値の型が前の行にある書き方（`static bool\nFoo(...)`）を補う。
        name = t["name"]
        head = text.split("(", 1)[0]
        if re.fullmatch(r"[\w:~]*" + re.escape(name) + r"\s*", head) and t.get("typeref"):
            tr = t["typeref"].split(":", 1)[-1]
            if tr:
                text = f"{tr} {text}"
        # テンプレートの頭が前の行にある場合を補う。
        prev = strip_comments(lines[idx - 1]).strip() if idx > 0 else ""
        if prev.startswith("template") and prev.endswith(">") and not text.startswith("template"):
            text = f"{prev} {text}"
    return tidy(text)


_anon = re.compile(r"__anon[0-9a-f]+")


def qualified(t):
    scope = t.get("scope")
    # ctags は .cpp の定義に `Foo::Bar` の形でしか scope を付けないことがあるので、そのまま繋ぐ。
    name = f"{scope}::{t['name']}" if scope else t["name"]
    # 無名の enum / union に ctags が振る名前（`__anon57e3311c1803`）はハッシュで、
    # 前後の行が動くだけで変わる。索引の差分がそれで埋まらないよう伏せる。
    return _anon.sub("(anonymous)", name)


# --- 書き出し --------------------------------------------------------------

def md_code(text):
    """インラインコードで囲む。本文にバッククォートがあれば囲いを伸ばす。"""
    if not text:
        return ""
    run = max((len(m) for m in re.findall(r"`+", text)), default=0)
    fence = "`" * (run + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def index_file_for(path):
    """SDKLib からの相対パス → 索引ファイル（ディレクトリ 1 つにつき 1 枚）。"""
    d = os.path.dirname(path)
    return (d if d else "(root)") + ".md"


def write_cpp_index(sdklib, tags, out_dir):
    by_file = collections.defaultdict(list)
    for t in tags:
        by_file[t["path"]].append(t)

    by_index = collections.defaultdict(list)
    for path in by_file:
        by_index[index_file_for(path)].append(path)

    summary = []
    for index_rel in sorted(by_index):
        paths = sorted(by_index[index_rel])
        dir_rel = index_rel[: -len(".md")]
        out = [
            GENERATED_MARK,
            "",
            f"# `SDKLib/{dir_rel}`",
            "",
            "Vectorworks SDK の宣言索引（コメントと本体は含まない）。見方は"
            " [SDK Index の README](" + "../" * dir_rel.count("/") + "README.md) を参照。",
            "",
        ]
        count = 0
        for path in paths:
            base = os.path.basename(path)
            out.append(f"## {base}")
            out.append("")
            for t in sorted(by_file[path], key=lambda x: (x["line"], KIND_ORDER.index(x["kind"]), x["name"])):
                decl = decl_of(sdklib, t) or t["kind"]
                loc = f"{base}:{t['line']}"
                out.append(f"- {md_code(loc)} {t['kind']} {md_code(qualified(t))} — {md_code(decl)}")
                count += 1
            out.append("")
        dest = os.path.join(out_dir, index_rel)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out).rstrip("\n") + "\n")
        summary.append((index_rel, len(paths), count))
    return summary


# vs.py の 1 関数: def 行・Python / VectorScript の書式行・分類。
_vs_def = re.compile(r"^def (\w+)\(")
_vs_python = re.compile(r"^\s*Python:\s*(.*\S)\s*$")
_vs_vscript = re.compile(r"^\s*VectorScript:\s*(.*\S)\s*$")
_vs_category = re.compile(r"^\s*Category:\s*(.*\S)\s*$")


def write_vectorscript_index(sdklib, out_dir):
    path = os.path.join(sdklib, "Include", "vs.py")
    if not os.path.isfile(path):
        return None
    lines = source_lines(sdklib, "Include/vs.py")
    rows = []
    cur = None
    for i, line in enumerate(lines):
        m = _vs_def.match(line)
        if m:
            if cur:
                rows.append(cur)
            cur = {"name": m.group(1), "line": i + 1, "py": "", "vs": "", "cat": ""}
            continue
        if cur is None:
            continue
        for key, rx in (("py", _vs_python), ("vs", _vs_vscript), ("cat", _vs_category)):
            if not cur[key]:
                mm = rx.match(line)
                if mm:
                    cur[key] = mm.group(1)
    if cur:
        rows.append(cur)

    def cell(text):
        return md_code(text.replace("|", "\\|")) if text else ""

    out = [
        GENERATED_MARK,
        "",
        "# VectorScript / Python（`SDKLib/Include/vs.py`）",
        "",
        "`vs.py` に並ぶ関数の書式と分類（説明文は含まない）。ISDK との対応は"
        " [Findings「VectorScript to SDK Mapping」](../Findings/VectorScript%20to%20SDK%20Mapping.md) を参照。",
        "",
        "| 名前 | VectorScript | Python | 分類 | 行 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in sorted(rows, key=lambda r: (r["name"].lower(), r["line"])):
        out.append(f"| {r['name']} | {cell(r['vs'])} | {cell(r['py'])} | {r['cat'].replace('|', '/')} | {r['line']} |")
    with open(os.path.join(out_dir, "VectorScript.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return len(rows)


def clean_generated(out_dir):
    """前回の生成物（印付きの .md）だけを消す。手書きの README などは残す。"""
    if not os.path.isdir(out_dir):
        return
    for root, _dirs, files in os.walk(out_dir):
        for name in files:
            if not name.endswith(".md"):
                continue
            p = os.path.join(root, name)
            with open(p, encoding="utf-8", errors="replace") as f:
                first = f.readline().rstrip("\n")
            if first == GENERATED_MARK:
                os.remove(p)
    # 空になったディレクトリを畳む（深い方から）。
    for root, dirs, files in os.walk(out_dir, topdown=False):
        if root != out_dir and not os.listdir(root):
            os.rmdir(root)


def main():
    if len(sys.argv) != 3:
        die("usage: sdk-index.py <SDK_DIR> <OUT_DIR>")
    sdk_dir, out_dir = sys.argv[1], sys.argv[2]
    sdklib = os.path.join(sdk_dir, "SDKLib")
    if not os.path.isfile(os.path.join(sdklib, "Include", "VectorworksSDK.h")):
        die(f"SDK が見つかりません: {sdklib}/Include/VectorworksSDK.h")
    if shutil.which("ctags") is None:
        die("ctags（universal-ctags）がありません")

    ver = subprocess.run(["ctags", "--version"], capture_output=True, text=True).stdout
    if "Universal Ctags" not in ver:
        die("ctags が universal-ctags ではありません")

    tags = run_ctags(sdklib)
    os.makedirs(out_dir, exist_ok=True)
    clean_generated(out_dir)
    summary = write_cpp_index(sdklib, tags, out_dir)
    vs_count = write_vectorscript_index(sdklib, out_dir)

    # 目次（生成物）。SDK の出所は fetch-vw-sdk.sh が残した sdk-origin.txt から。
    origin = {}
    origin_path = os.path.join(sdk_dir, "sdk-origin.txt")
    if os.path.isfile(origin_path):
        with open(origin_path, encoding="utf-8") as f:
            for line in f:
                if "=" in line:
                    k, v = line.rstrip("\n").split("=", 1)
                    origin[k] = v

    kinds = collections.Counter(t["kind"] for t in tags)
    out = [
        GENERATED_MARK,
        "",
        "# 目次（生成物）",
        "",
        "索引の読み方と運用は [README](README.md)。",
        "",
        "## 元にした SDK",
        "",
        "| | |",
        "| --- | --- |",
        f"| SDK の版（zip 内のフォルダ名） | {md_code(origin.get('folder', '(不明)'))} |",
        f"| 取得元 | {origin.get('url', '(不明)')} |",
        f"| Last-Modified | {origin.get('last_modified', '(不明)')} |",
        f"| ETag | {md_code(origin.get('etag', '(不明)'))} |",
        f"| ctags | {md_code(ver.splitlines()[0].strip())} |",
        "",
        "## 件数",
        "",
        "| 種類 | 件数 |",
        "| --- | ---: |",
    ]
    for k in KIND_ORDER:
        if kinds.get(k):
            out.append(f"| {k} | {kinds[k]} |")
    out.append(f"| **計** | **{sum(kinds.values())}** |")
    if vs_count is not None:
        out.append(f"| VectorScript 関数（`vs.py`） | {vs_count} |")
    out += [
        "",
        "## ファイル",
        "",
        "| 索引 | 原本のファイル数 | 件数 |",
        "| --- | ---: | ---: |",
    ]
    if vs_count is not None:
        out.append(f"| [VectorScript.md](VectorScript.md) | 1 | {vs_count} |")
    for index_rel, nfiles, count in summary:
        link = index_rel.replace(" ", "%20").replace("(", "%28").replace(")", "%29")
        out.append(f"| [{index_rel}]({link}) | {nfiles} | {count} |")
    with open(os.path.join(out_dir, "INDEX.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    print(f"sdk-index: {sum(kinds.values())} declarations in {len(summary)} index files"
          f" (+ {vs_count or 0} VectorScript functions) -> {out_dir}")


if __name__ == "__main__":
    main()
